# Generated by Django 5.0.6 on 2026-07-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('instance_name', models.CharField(db_index=True, max_length=100)),
                ('push_name', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('in_service', 'Em atendimento'), ('closed', 'Encerrado')], default='new', max_length=20)),
                ('is_ai_paused', models.BooleanField(default=False)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone', 'instance_name'], name='contacts_co_phone_e5e5b0_idx')],
                'unique_together': {('phone', 'instance_name')},
            },
        ),
    ]
