# Generated by Django 5.0.6 on 2026-07-18 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente (IA)'), ('agent', 'Atendente humano')], max_length=10)),
                ('content', models.TextField()),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.contact')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
